'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..');
const src=fs.readFileSync(path.join(root,'content','catalog.js'),'utf8');
const sandbox={window:{}};vm.createContext(sandbox);vm.runInContext(src,sandbox);
vm.runInContext(fs.readFileSync(path.join(root,'learning-v2.js'),'utf8'),sandbox);
const R=sandbox.window.OTTO_FULL_LEARNING;
assert.equal(R.allTasks().filter(x=>x.module==='Lesen').length,50);
assert.equal(R.allTasks().filter(x=>x.module==='Hören').length,40);
const state={dailyMinutes:25,task_history:{},dailySession:{completed:[]}};
const result={profiles:{Lesen:{status:'SUPPORTED'},Hören:{status:'NEED_CONFIRMATION'},Schreiben:{status:'SUPPORTED'},Sprechen:{status:'SUPPORTED'}},gaps:[{module:'Hören'}]};
const p=R.buildPlan(state,result);assert.ok(p.plan.length>=2);assert.equal(p.plan.some(x=>x.module==='Hören'),true);
const short={dailyMinutes:10,task_history:{},dailySession:{completed:[]}};const p10=R.buildPlan(short,result);assert.equal(p10.plan.length,1);assert.equal(p10.plan[0].module,'Hören','weak skill must win short session');
const medium={dailyMinutes:25,task_history:{},dailySession:{completed:[]}};const p25=R.buildPlan(medium,result);assert.ok(p25.plan.length>=2&&p25.plan.length<=3);
const long={dailyMinutes:45,task_history:{},dailySession:{completed:[]}};const p45=R.buildPlan(long,result);assert.ok(p45.plan.length>=4&&p45.plan.length<=5);
const inTen=new Date(Date.now()+10*86400000).toISOString().slice(0,10);const urgent={dailyMinutes:25,examDate:inTen,task_history:{},dailySession:{completed:[]}};assert.ok(R.daysUntilExam(urgent)<=10&&R.daysUntilExam(urgent)>=9);assert.ok(R.buildPlan(urgent,result).plan.length>=2);
const first=R.currentSessionTask(state);assert.ok(first&&first.task_id);
R.recordCompletion(state,first,{score:.8,assistance_used:false});assert.equal(state.task_history[first.task_id].attempt_count,1);assert.ok(state.task_history[first.task_id].next_review);
const tomorrow={...state,dailyMinutes:25,dailySession:{completed:[]}};const old=tomorrow.task_history[first.task_id];old.last_seen=new Date(Date.now()-86400000).toISOString().slice(0,10);old.next_review=new Date(Date.now()+4*86400000).toISOString().slice(0,10);const next=R.buildPlan(tomorrow,result);assert.notEqual(next.plan[0].task_id,first.task_id,'task before next_review should not immediately repeat');
console.log('learning-v2 planner regression: PASS');
