function diagnosticMc(taskId,label){const task=TASKS[taskId];return diagShell(label,`${task.text?`<div class="p1-task">${h(task.text)}</div>`:''}${task.audio?`<button class="btn secondary" onclick="p1Play('${task.audio}')">▶ Воспроизвести аудио</button>`:''}${translationButton(taskId)}<p><b>${h(task.prompt)}</b></p>${task.options.map((x,i)=>`<button class="option ${p().ui.choice===i?'sel':''}" onclick="p1Choose(${i})">${h(x)}</button>`).join('')}<button class="btn primary" onclick="p1DiagMC('${taskId}')">Продолжить</button>`);}

function diagnosticReport(){updateSkills();const st=p();const pri=st.route.priorities.slice(0,3);return `<span class="eyebrow">Диагностический отчёт</span><h1 class="h1">Что уже видно — и чего пока не видно</h1>${card('Текущая языковая зона',baselineZone(),'soft')}<div class="p1-strip">${MODULES.map(m=>{const s=moduleSummary(m);return `<div><b>${m}</b>${s.label}</div>`}).join('')}</div>${MODULES.map(m=>{const s=moduleSummary(m);return `<div class="card"><div class="p1-skill"><div><b>${m}</b><p class="sub">${h(s.detail)}</p></div><span class="p1-state ${s.cls}">${h(s.label)}</span></div></div>`}).join('')}${card('Важно','Это предварительный профиль. По большинству навыков данных ещё недостаточно для вывода о готовности B1.','warn')}<h3>Ближайшие приоритеты</h3>${pri.map(priorityCard).join('')||card('Пока нет приоритетов','Нужно пройти диагностические probes.') }<button class="btn primary" onclick="p1StartRoute()">Открыть мой маршрут</button>`;}

function routeView(){updateSkills();const st=p();const pri=st.route.priorities.slice(0,4);const due=st.reviews.filter(r=>r.status!=='done').length;return `<span class="eyebrow">Персональный маршрут</span><h1 class="h1">Что тренируем сейчас и почему</h1>${pri.map(priorityCard).join('')||card('Нужно больше данных','Пройди диагностику, чтобы Otto выбрал приоритеты.','soft')}${card('Повторения',due?`Запланировано: ${due}`:'Пока нет due-повторов')}${card('Что дальше','После новой ошибки, transfer-проверки или weekly checkpoint порядок пересчитывается автоматически.')}<div class="p1-toolbar"><button class="btn secondary" onclick="p1SetDuration(10)">10 мин</button><button class="btn secondary" onclick="p1SetDuration(25)">25 мин</button></div><button class="btn secondary" onclick="p1SetDuration(45)">45 минут</button><button class="btn primary" onclick="p1StartDaily()">Начать сегодняшнюю тренировку</button><button class="btn ghost" onclick="p1StartCheckpoint()">Weekly checkpoint · пересчитать маршрут</button>`;}

function dailyView(){const st=p();const d=st.daily;if(!d.active&&d.completed)return R['p1-daily-summary']();const action=d.queue[d.cursor]||{kind:'priority',module:'Lesen',skill:'L.T1.CORR.M05'};st.ui.exam=action.kind==='examlike';let body=`<span class="eyebrow">Сегодня · шаг ${d.cursor+1} из ${d.queue.length}</span><h1 class="h1">${action.kind==='review'?'Повторение':action.kind==='examlike'?'Самостоятельная exam-like проверка':'Главный приоритет'}</h1>`;if(action.kind==='review'){const reviewTaskId=lesenTransferTaskId(action.skill);body+=card('Почему сейчас','Это навык, который пора проверить после исправления.','soft')+renderTask(reviewTaskId,{title:'Lesen · повторение',mode:'review',next:'p1-daily'}).replace(`p1Submit('${reviewTaskId}','p1-daily','','review')`,`p1SubmitDaily('${reviewTaskId}','review')`);return body;}
  if(action.kind==='examlike'){body+=`<div class="notice">Без подсказок и перевода. Разбор будет после ответа.</div>`+renderTask('exam-lesen',{title:'Exam-like · Lesen',mode:'exam_like',next:'p1-daily'}).replace("p1Submit('exam-lesen','p1-daily','','exam_like')","p1SubmitDaily('exam-lesen','exam_like')");return body;}
  if(action.module==='Hören')return body+card('Почему сейчас',action.skill===st.route.priorities[0]?.skill?st.route.priorities[0].why:'Текущий приоритет маршрута','soft')+renderTask('train-hoeren',{mode:'training',next:'p1-daily'}).replace("p1Submit('train-hoeren','p1-daily','','training')","p1SubmitDaily('train-hoeren','training')");
  if(action.module==='Schreiben')return body+card('Почему сейчас',st.route.priorities[0]?.why||'Нужен новый письменный образец.','soft')+`<div class="p1-task"><b>Du konntest gestern nicht zu einem Treffen kommen.</b><p>Schreib 70–90 Wörter: Entschuldige dich, nenne einen Grund und schlage einen neuen Termin vor.</p></div><textarea id="p1dailyw" class="field" rows="7" placeholder="Schreibe auf Deutsch…"></textarea><button class="btn primary" onclick="p1SubmitDailyWriting()">Сохранить и продолжить</button>`;
  if(action.module==='Sprechen')return body+card('Почему сейчас',st.route.priorities[0]?.why||'Нужно проверить взаимодействие.','soft')+`<p class="sub">Sprechen Aufgabe 1: вместе с Otto спланируй маленький праздник.</p><button class="btn primary" onclick="p1OpenDailySpeaking()">Открыть парную тренировку</button>`;
  const lesenTaskId=lesenPracticeTaskId(action.skill);return body+card('Почему сейчас',st.route.priorities[0]?.why||'Текущий приоритет маршрута','soft')+renderTask(lesenTaskId,{mode:'training',next:'p1-daily'}).replace(`p1Submit('${lesenTaskId}','p1-daily','','training')`,`p1SubmitDaily('${lesenTaskId}','training')`);}
window.p1SubmitDaily=(taskId,mode)=>{const st=p();if(st.ui.choice==null)return alert('Выбери ответ');const task=TASKS[taskId];const ok=st.ui.choice===task.correct;recordEvidence(taskId,ok,{mode,selected:st.ui.choice});st.ui.choice=null;st.ui.exam=false;if(!ok){const err=addError(taskId,task.trap);st.ui.activeErrorId=err.id;persist();if(task.module==='Lesen')go('p1-repair');else go('p1-error-note');return;}persist();p1DailyNext();};
window.p1SubmitDailyWriting=()=>{const t=(by('p1dailyw')?.value||'');const v=writingValidity(t);if(!v.ok)return alert(v.msg);addGenericEvidence('W.A1.CONTACT.M02','Schreiben',v.covered===3,'training',{wordCount:v.words,functions:v.functions});persist();p1DailyNext();};
