function updateSkills(){const st=p();Object.keys(SKILL_META).forEach(id=>{const ev=st.diagnostic.evidence.filter(x=>x.skill===id).concat(st.exam.answers.filter(x=>x.skill===id));const independent=ev.filter(x=>!x.assisted&&!x.unscored&&x.mode!=='guided');const correct=independent.filter(x=>x.ok).length;let state='insufficient';if(independent.length>=3){const rate=correct/independent.length;state=rate>=.8?'stable':rate>=.55?'unstable':'weak';}else if(independent.length>=2&&correct===0)state='weak';st.skills[id]={checks:independent.length,correct,failures:independent.length-correct,lastAt:ev.length?ev[ev.length-1].at:null,state,confidence:independent.length>=4?'enough':independent.length>=2?'low':'insufficient'};});rebuildRoute();persist();}
function rebuildRoute(){const st=p();const priorities=[];Object.entries(st.skills).forEach(([id,x])=>{const m=SKILL_META[id];if(!m||m.module==='Basis')return;let score=x.state==='weak'?100:x.state==='unstable'?70:x.state==='insufficient'?45:20;const err=st.errors.filter(e=>e.skill===id&&e.status!=='resolved').length;score+=err*20;if(st.reviews.some(r=>r.skill===id&&new Date(r.dueAt).getTime()<=Date.now()))score+=30;priorities.push({skill:id,module:m.module,label:m.label,score,why:x.state==='weak'?'Есть повторная ошибка или провал.':x.state==='unstable'?'Результат пока нестабилен.':x.state==='insufficient'?'Нужно собрать больше независимых данных.':'Поддерживающее повторение.'});});priorities.sort((a,b)=>b.score-a.score||a.skill.localeCompare(b.skill));st.route.priorities=priorities;st.route.updatedAt=iso();}
function moduleSummary(module){const ids=Object.keys(SKILL_META).filter(id=>SKILL_META[id].module===module);const states=ids.map(id=>p().skills[id]||{state:'insufficient',checks:0});const checks=states.reduce((n,x)=>n+x.checks,0);if(!checks)return{label:'Недостаточно данных',cls:'p1-unknown',detail:'Нужны реальные независимые попытки.'};if(states.some(x=>x.state==='weak'))return{label:'Есть риск',cls:'p1-risk',detail:'Обнаружен слабый микронавык. Нужна перепроверка.'};if(states.every(x=>x.state==='stable')&&checks>=6)return{label:'Есть подтверждение',cls:'p1-ok',detail:'Есть несколько независимых подтверждений. Это не официальный балл Goethe.'};return{label:'Нужно подтверждение',cls:'',detail:'Данных пока мало или они нестабильны.'};}
function baselineZone(){const a=p().skills['BASE.GRAMMAR.ORDER'],b=p().skills['BASE.VOCAB.CORE'];if(!a||!b||a.checks+b.checks<2)return'Недостаточно данных';const ok=(a.correct||0)+(b.correct||0);return ok===2?'Примерно B1-вход: нужен экзаменационный профиль':ok===1?'Переходная зона A2+/B1: нужен дополнительный baseline':'Языковая база требует усиления до экзаменационной работы';}
function priorityCard(x,i){return `<div class="card"><div class="p1-skill"><div><b>${i+1}. ${h(x.module)} · ${h(x.label)}</b><p class="sub">${h(x.why)}</p></div><span class="p1-state">в фокусе</span></div></div>`;}
function translationButton(taskId){if(p().ui.exam)return'';const task=TASKS[taskId];if(!task||!task.translation)return'';const open=!!p().ui.translation[taskId];return `<button class="p1-chip" onclick="p1ToggleTranslation('${taskId}')">${open?'👁 Скрыть перевод':'👁 Перевод'}</button>${open?`<div class="notice">${h(task.translation)}</div>`:''}`;}
function strategyBox(taskId){if(p().ui.exam)return'';const open=!!p().ui.strategy[taskId];const task=TASKS[taskId];return `<button class="p1-chip" onclick="p1ToggleStrategy('${taskId}')">☝ ${open?'Скрыть стратегию':'Стратегия Отто'}</button>${open?`<div class="notice"><b>Как действовать:</b> сначала определи, что проверяет вопрос, затем ищи смысловое доказательство. <br><b>Типичная ловушка:</b> ${h(task.trap||'Не выбирай ответ только из-за знакомого слова.')}</div>`:''}`;}
function renderTask(taskId,opts={}){const task=TASKS[taskId];const title=opts.title||`${task.module}${SKILL_META[task.skill]?.teil?' · '+SKILL_META[task.skill].teil:''}`;let html=`<span class="eyebrow">${h(title)}</span><h1 class="h1">${h(SKILL_META[task.skill]?.label||task.prompt)}</h1>`;if(task.text)html+=`<div class="p1-task">${h(task.text)}</div>`;if(task.audio)html+=`<div class="p1-audio"><button class="btn secondary" onclick="p1Play('${task.audio}')">▶ Воспроизвести аудио</button></div><div class="p1-overlay-note">Аудио предзагружено. Стандартная тренировка не вызывает AI/API.</div>`;html+=translationButton(taskId);html+=strategyBox(taskId);html+=`<p><b>${h(task.prompt)}</b></p>`+task.options.map((x,i)=>`<button class="option ${p().ui.choice===i?'sel':''}" onclick="p1Choose(${i})">${h(x)}</button>`).join('');html+=`<button class="btn primary" onclick="p1Submit('${taskId}','${opts.next||''}','${opts.wrong||''}','${opts.mode||'training'}')">Ответить</button>`;return html;}
function addError(taskId,reason){const task=TASKS[taskId];let err=p().errors.find(e=>e.skill===task.skill&&e.status!=='resolved');if(err){err.recurrence=(err.recurrence||0)+1;err.lastAt=iso();err.reason=reason||err.reason;err.status='active';return err;}err={id:'err-'+now(),taskId,skill:task.skill,module:task.module,reason:reason||task.trap||'Нужно перепроверить смысл.',status:'active',createdAt:iso(),lastAt:iso(),recurrence:0,repairAttempts:0,transferPassed:false};p().errors.push(err);return err;}
function nextDiag(){const st=p();st.diagnostic.cursor+=1;if(st.diagnostic.cursor>=DIAG_STEPS.length){const lesenFail=st.diagnostic.evidence.some(e=>e.taskId==='d-lesen'&&!e.ok);if(lesenFail&&!st.diagnostic.adaptiveDone){st.diagnostic.adaptiveDone=true;persist();go('diag-p1-adaptive');return;}st.diagnostic.completed=true;updateSkills();go('diag-p1-report');return;}go(DIAG_STEPS[st.diagnostic.cursor].screen);}
function lesenPracticeTaskId(skill){return skill==='L.T1.CORR.M04'?'train-lesen-paraphrase':'train-lesen';}
function lesenTransferTaskId(skill){return skill==='L.T1.CORR.M04'?'transfer-lesen-paraphrase':'transfer-lesen';}
function diagnosticProgress(){return Math.min(100,Math.round((p().diagnostic.cursor/DIAG_STEPS.length)*100));}
function diagShell(label,inner){return `<span class="eyebrow">Диагностика · ${diagnosticProgress()}%</span><div class="bar"><i style="width:${diagnosticProgress()}%"></i></div><h1 class="h1">${h(label)}</h1>${inner}`;}
function writingValidity(t){const text=(t||'').trim();if(!text)return{ok:false,msg:'Ответ пустой — данных для Schreiben нет.'};if(/[А-Яа-яЁё]/.test(text)&&!(text.match(/[A-Za-zÄÖÜäöüß]/g)||[]).length)return{ok:false,msg:'Текст написан не по-немецки — он не может быть доказательством Schreiben B1.'};const german=(text.match(/\b(ich|wir|leider|weil|deshalb|aber|möchte|kann|können|treffen|Termin|Uhr|kommen|entschuldige|Entschuldigung|vielleicht|würde|könnten)\b/gi)||[]).length;const words=(text.match(/[A-Za-zÄÖÜäöüß]+/g)||[]).length;if(words<18||german<2)return{ok:false,msg:'Пока слишком мало осмысленного немецкого текста для диагностического вывода.'};const functions={apology:/entschuldig|leider/i.test(text),reason:/weil|wegen|da\b|denn/i.test(text),proposal:/könn|möcht|vielleicht|wie wäre|treffen/i.test(text)};const covered=Object.values(functions).filter(Boolean).length;return{ok:true,words,functions,covered,msg:covered>=2?'Есть пригодный образец, но одного текста недостаточно для оценки готовности.':'Текст осмысленный, но коммуникативные пункты покрыты не полностью.'};}
